### ISSUE TITLE
Watcher Not working 

### ISSUE THREAD

**Issue by sreejithseradi** [elastic/elasticsearch-net#2627]
Below is the watcher config put through sense

```json
PUT watcher/watch/Email_watch
{
	"trigger": {
		"schedule": {
			"interval": "1m"
		}
	},
	"input": {
		"search": {
			"request": {
				"indices": "logstash-2017.02.20",
				"body": {
					"size": 0,
					"query": {
						"range": {
							"syslog_sev_level": {
								"lte": "6 "
							}
						}
					}
				}
			}
		}
	},
	"condition": {
		"script": "return ctx.payload.hits.total > 0"
	},
	"actions": {
		"send_email": {
			"throttle_period": "60m",
			"email": {
				"to": "sreejith@XXX.com",
				"from": "elk-notification@XXX.com",
				"subject": "Syslog_sev_level less than or equal to 5",
				"body": "Syslog_sev_level less than or equal to 5",
				"attachments": {
					"attached_data": {
						"data": {
							"format": "json"
						}
					}
				},
				"priority": "high"
			}
		}
	}
}
```

Below is the Curl output
XXXX@ubuntu:/usr/share/elasticsearch/config$ curl -XGET 'http://localhost:9200/_watcher/stats?pretty'

```json
{
	"watcher_state": "started",
	"watch_count": 2,
	"execution_thread_pool": {
		"queue_size": 0,
		"max_size": 15
	},
	"manually_stopped": false
}
```

Elasticsearch.yml config:

```yaml
watcher.index.rest.direct_access : true
watcher.actions.email.service.account:
exchange_account:
profile: outlook
email_defaults:
from: ELK-dc-notiifcations@XXX.com
smtp:
auth: false
starttls.enable: false
host: Smtp.1bank.XXX.com
port: 25
user: ELK-dc-notiifcations@XXX.com
password:
```

Below is the versions been used ..

Kibana Version 4.5.4
elasticsearch 2.4.2
Logstash 2.3.4
Watcher 2.4.4.

Email for some reason is not been initiated ..Anyone can help if possible
