### ISSUE TITLE
Cannot assign  request address 

### ISSUE THREAD

**Issue by laosandegudai** [elastic/elasticsearch-net#3787]
**NEST/Elasticsearch.Net version**:6.6

**Elasticsearch version**:6.7

**Description of the problem including expected versus actual behavior**:
When big data index 
![IB BIMMD}BWZPNM930NK}OK](https://user-images.githubusercontent.com/17979159/58689415-8f6d3c80-83b9-11e9-8805-207896d84c3b.png)

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:
          var path = Environment.GetEnvironmentVariable("ESURL");
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new Exception("the Environment vairable ESURL is not exist");
            }

            var pathArr = path.Split(",", StringSplitOptions.RemoveEmptyEntries);
            IEnumerable<Uri> nodes = pathArr.ToList().Select(s => new Uri(s));
            var pool = new StaticConnectionPool(nodes);
            var settings = new ConnectionSettings(pool).DefaultTypeName(ESClient.DOCUMENTTYPE).ConnectionLimit(1000);
**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
This looks like an issue in your environment @laosandegudai. What does `http://es:9200` resolve to?

**Comment by laosandegudai** [comment]
> This looks like an issue in your environment @laosandegudai. What does `http://es:9200` resolve to?
My   environment  is  right ,it  works well a little ,    alaways  happyend    one  hour  time after   running.

**Comment by biaotang** [comment]
@russcam  
Through the command ```netstat -n | grep 9200 | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'``` on the application docker container, I found many ESTABLISHED tcp connection when large amount of data was inserting into es,  nest client  doesn't  release or close the tcp connection.  The  value of ESTABLISHED connection  grows to  20 thousand.  Doesn't  the nest client reuse the connection ?

**Comment by Mpdreamz** [comment]
It should @biaotang can you share more about the docker images and host?

**Comment by Mpdreamz** [comment]
Also be sure you adhere to our lifetime guidelines:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/lifetimes.html

Reusing HttpClient is per `ConnectionSettings`

**Comment by biaotang** [comment]
> It should @biaotang can you share more about the docker images and host?

I am sorry to reply so late.

The information related deployment environment  as follow:

```
[root@node1 ~]# docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

.net application named  edoc2,  image built  base  on  dotnet-runtime-2.1.0


es image :   docker.elastic.co/elasticsearch/elasticsearch:6.7.2
 

(deployed using  ```docker stack```)  compose file  as follow: 

```
version: '3.3'

services:
  edoc2:
    hostname: edoc2
    image: 192.168.251.78/edoc2v5/edoc2:20190530195516
    labels:
      "type": "1"
    environment:
      - ESURL=http://es:9200
    networks: 
      - edoc2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    hostname: es
    volumes:
      - /home/edoc2/data/es:/usr/share/elasticsearch/data
    labels:
      "type": "2"
    networks: 
      - edoc2
    environment:
      - node.name=es
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  edoc2:
    driver: overlay
```

code for ESClient :
```
public class ESClient
    {
        public const string ESSECTION = "ESClient";
        public const string ESURLS = "Urls";
        private static ConnectionSettings _defaultConnectionSettings;
        private ConnectionSettings _connectionSettings;
        private ElasticClient _elasticClient;
        public ESClient()
        {
            _connectionSettings = _defaultConnectionSettings;
        }
        public ESClient(IConfiguration configuration)
        {
            var urls = configuration.GetSection($"{ESSECTION}:{ESURLS}");
            if (!string.IsNullOrWhiteSpace(urls.Value))
            {
                var nodes = urls.Value.Split(';').Select(x => new Uri(x));
                var pool = new StaticConnectionPool(nodes);
                _connectionSettings = new ConnectionSettings(pool);
            }
        }

        public static void AddESClient(ConnectionSettings connectionSettings)
        {
            _defaultConnectionSettings = connectionSettings;
        }

        private void InitESClient()
        {
            if (_elasticClient == null)
            {
                if (_connectionSettings != null)
                {
                    _elasticClient = new ElasticClient(_connectionSettings);
                }
                else
                {
                    throw new Exception("ESClient init failed！");
                }
            }
        }
    }
```

code for ESClientProvider: 
```
public static class ESClientProvider
    {
        private static ESClient _client;

        public static ESClient GetESClient()
        {
            if (_client != null)
            {
                return _client;
            }

            var path = Environment.GetEnvironmentVariable("ESURL");
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new Exception("the Environment vairable ESURL is not exist");
            }
        
            var pathArr = path.Split(",", StringSplitOptions.RemoveEmptyEntries);
            IEnumerable<Uri> nodes = pathArr.ToList().Select(s=>new Uri(s));
            var pool = new StaticConnectionPool(nodes);
            var settings = new ConnectionSettings(pool).ConnectionLimit(1000);
            ESClient.AddESClient(settings);
            ESClient client = new ESClient();
            _client = client;
            return _client;
        }
    }
```

The application  created three instances  through ESClientProvider,  different instance doing different tasks. 

According to my understanding， every instance created limit the connection 1000  by the option connectionLimits,  three instances at most 3000 concurrent connections and then HttpClient will reuse the connection. Is it  right ?

However, I found 20,000 connections from edoc2 with the status ESTABLISHED
