### ISSUE TITLE
Proper way to use NEST SniffingPool and ES Docker installation?

### ISSUE THREAD

**Issue by IvanSorokin** [elastic/elasticsearch-net#3965]
**NEST/Elasticsearch.Net version**: 7.0.0

**Elasticsearch version**: 7.2.0

**Description**: We switched from the zip installation to the docker one. It works fine with direct curl requests but doesnt work with our C# app, throws timeout exception because of the problem with IP addresses. I searched simillar issues on SO and found [this workaround](https://stackoverflow.com/questions/48006720/accessing-elasticsearch-docker-instance-using-nest). It fixed problems and everything works fine now. But I am curious what is the proper way to use SniffingPool with docker? It is very useful for example for the local development, so you don't need to specify all nodes if you want to connect to our testing es. Is it possible? Should I change docker settings or something in my NEST configuration? 

**Steps to reproduce**:
 1.  [Install Elasticsearch via Docker and run](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
 2.  Specify SniffingPool in the connection settings
 3.  Try to use it via NEST client

**Comment by russcam** [comment]
`SniffingConnectionPool` will use the [`http.publish_address` of the node](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html#_settings) when seeded in the connection pool. This means that the http publish address must be reachable by the client. If it's not explicitly set, it'll use the value from `http.host`, which if not set, will use the `network.host`, which will be the address on the private network.

With a docker compose configuration like

```yml
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.port=9200"
      - "http.publish_host=_local_"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.port=9201"
      - "http.publish_host=_local_"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
```

`es01` node is mapped to `localhost:9200` and `es02` to `localhost:9201`. We could have just specified that `es02` runs in the container on 9200, and mapped this to the host port of 9201, but the problem with doing this is that `es02`'s http.publish_address would still be `127.0.0.1:9200`, which is what the `SniffingConnectionPool` will end up using when seeding the node. To avoid this, we run `es02` on a different port to `es01`, so that the http publish addresses will be different.

With the above configuration, `http://localhost:9200/_nodes?filter_path=nodes.*.http` returns 

```json
{
  "nodes": {
    "CSWncVnxS1esOm1KQtOR3A": {
      "http": {
        "bound_address": ["0.0.0.0:9200"],
        "publish_address": "127.0.0.1:9200",
        "max_content_length_in_bytes": 104857600
      }
    },
    "rOAp0T57TgSI_zU1L-T-vw": {
      "http": {
        "bound_address": ["0.0.0.0:9201"],
        "publish_address": "127.0.0.1:9201",
        "max_content_length_in_bytes": 104857600
      }
    }
  }
}
```

(_node names will be different if you try this_). Now, `SniffingConnectionPool` will work

```c#
private static void Main()
{
	var defaultIndex = "posts";
	var uris = new[]
	{
		new Uri("http://localhost:9200"),
		new Uri("http://localhost:9201")
	};

	var pool = new SniffingConnectionPool(uris);

	var settings = new ConnectionSettings(pool)
		.DefaultIndex(defaultIndex);

	var client = new ElasticClient(settings);

	var response = client.Nodes.Info();

	foreach (var node in response.Nodes)
	{
		Console.WriteLine($"{node.Key} http publish_address is: {node.Value.Http.PublishAddress}");
	}
}
```

prints

```
CSWncVnxS1esOm1KQtOR3A http publish_address is: 127.0.0.1:9200
rOAp0T57TgSI_zU1L-T-vw http publish_address is: 127.0.0.1:9201
```
