### ISSUE TITLE
Serilog.Sink.Elasticsearch, Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by Mehranh** [elastic/elasticsearch-net#6257]
I am using Serilog and Serilog.Sink.Elasticsearch in an ASP web API project, there is an issue with the connection to the ELK service that has been configured on an azure Kubernetes cluster, I get the error below when I deploy my code on the windows server 2012 R2, but it works on my desktop correctly, and SSL has been issued by LetsEncrypt and expiration time is fine

packages:

  ```
<package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net452" />
  <package id="Serilog" version="2.10.0" targetFramework="net472" />
  <package id="Elasticsearch.Net" version="7.17.0" targetFramework="net472" />
  <package id="Serilog.Sinks.Elasticsearch" version="8.4.1" targetFramework="net472" />
```
error:

> 2022-04-06T11:49:33.7509141Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: The request was aborted: Could not create SSL/TLS secure channel.. Call: Status code unknown from: POST /_bulk ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
> 
> at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
> 
> at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
> 
> --- End of stack trace from previous location where exception was thrown ---
> 
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 
> at Elasticsearch.Net.HttpWebRequestConnection.d__5`1.MoveNext()
> 
> --- End of inner exception stack trace ---
> 
> at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
> 
> at Elasticsearch.Net.Transport1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List1 seenExceptions, TResponse response)
> 
> at Elasticsearch.Net.Transport1.<RequestAsync>d__151.MoveNext()
> 
> --- End of stack trace from previous location where exception was thrown ---
> 
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 
> at Serilog.Sinks.Elasticsearch.ElasticsearchSink.d__2.MoveNext()

I've added these lines to Application_Start but it doesn't work me:

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;
            ServicePointManager.Expect100Continue = true;
```
Any thoughts?

**Comment by stevejgordon** [comment]
Hi, @Mehranh. `Serilog.Sink.Elasticsearch` is a third-party package that we (Elastic) do not directly support. Any issues with that library need to be raised in its [repository](https://github.com/serilog-contrib/serilog-sinks-elasticsearch) as a starting point.

That said, this appears to be a TLS error from the low-level client so I will try to help. It appears that the client and server are unable to negotiate TLS. Your server is quite old and may not have the appropriate TLS version(s) enabled (see this [article](https://www.admin-enclave.com/en/articles/windows/305-enable-tls-1-2-on-windows-2012-r2.html) I found for TLS 1.2). It also does not support TLS 1.3 and newer cypher suites. You will need to begin by verifying that the server running your client application and Elasticsearch support the same TLS requirements. 

What is your Elasticsearch server version?
Which version of the .NET Framework runtime is installed on your server?

**Comment by stevejgordon** [comment]
Hi again @Mehranh. Just checking in to see if this is still and issue for you and whether you can provide more details to assist further?

**Comment by Mehranh** [comment]
Hi , 

I resolved the issue by configuring the ingress to support the legacy TTLS , you can use this ConfigMap :

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA"
  ssl-protocols: "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3"
```

for more information please follow this [link](https://kubernetes.github.io/ingress-nginx/user-guide/tls/)
