### ISSUE TITLE
ExistsResponse.IsValid == false when index does not exist

### ISSUE THREAD

**Issue by SzymonKatra** [elastic/elasticsearch-net#6261]
**NEST**: 7.17.0

**Elasticsearch version**: 8.1.2

**.NET runtime version**: .NET Framework 4.7.1

**Operating system version**: Windows 10 Enterprise, Version 1909, OS build 18363.2037

**Description of the problem including expected versus actual behavior**:
When index does not exists and `ElasticClient.Indices.ExistsAsync` is called, property `IsValid` on `ExistsResponse` is set to false. `ApiCall`.`Success` is true (as expected)

**Expected behavior**
IsValid == true

![image](https://user-images.githubusercontent.com/4078086/162446465-db31f92f-16ab-4afc-bbeb-f5017a6dd218.png)

**Provide `DebugInformation` (if relevant)**:
```
Invalid NEST response built from a successful (404) low level call on HEAD: /item-en?pretty=true&error_trace=true
# Warnings:
- The client is unable to verify that the server is Elasticsearch due to security privileges on the server side. Some functionality may not be compatible if the server is running an unsupported product.
# Audit trail of this API call:
 - [1] HealthyResponse: Node: https://test-searchintexing.es.europe-west4.gcp.elastic-cloud.com:9243/ Took: 00:00:00.0767633
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# TCP states:
  CloseWait: 1
  Established: 82
  TimeWait: 13

# ThreadPool statistics:
  Worker: 
    Busy: 1
    Free: 32766
    Min: 8
    Max: 32767
  IOCP: 
    Busy: 1
    Free: 999
    Min: 8
    Max: 1000


```
